version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/v1"

    groups:
      dependencias-gerais:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
